- README.md
- config/log-viewer.php
Hello Arunas,
This PR adds some basic tests and does not introduce any breaking changes.
I have formatted the config file `log-viewer.php` to match Laravel standards and update the `README` to match these changes and grouping sections install-usage-configure.
I like the screenshot on top - it adds value, so I have added a small menu to provide the user a quick way to the installation process.
<p align="center">
</p>
--- 
Please let me know if any change is required.
Greetings and thanks,
Dan
> [ENHANCEMENT] Config file & README

- composer.json
- tests/Feature/HomePageTest.php
- tests/Feature/LogViewerTest.php
- tests/Feature/RoutesTest.php
- tests/Pest.php
- tests/TestCase.php
Hello Arunas,
This PR adds some basic tests and does not introduce any breaking changes.
<p align="center">
</p>
I propose some basic but important tests. I thought to keep it short due to the release. The package will receive feedback and contributions, and I don't generate a complex or unproductive scenario at this stage.
With this in mind, I must say that my next intention was to write tests for the Livewire components.
Tests are written in [Pest PHP](https://pestphp.com/) and make use of the following features and plugins:
- [Custom Helpers](https://pestphp.com/docs/helpers)
- [Setup and Teardown](https://pestphp.com/docs/setup-and-teardown)
- [Pest Laravel Functions](https://pestphp.com/docs/plugins/laravel)
---
Please let me know if any change is required.
Greetings and thanks,
Dan
> [TESTS] Add basic tests

- src/Http/Livewire/LogList.php
Hi 👋
I watched how Telescope fights it. Therefore, I fixed it here as well
#9
> Fix Laravel Octane

- composer.json
> Fix conflict

- README.md
- https://github.com/opcodesio/log-viewer/discussions/17
- https://github.com/opcodesio/log-viewer/discussions/16
- https://github.com/opcodesio/log-viewer/discussions/6
> docs: (readme) add auth section

- composer.json
- src/LogViewerServiceProvider.php
Removed Spatie Package Tools as a dependency
This package was using relatively few features of the spatie packages tools, those can be implemented directly in the package to eliminate 1 dependency
> Removed Spatie Package Tools

- resources/css/app.scss
This will change the scrollbars from OS defaults into the dark variant when the app is in darkmode.
> Use dark scrollbars when in darkmode

- resources/views/pagination.blade.php
fixes https://github.com/opcodesio/log-viewer/issues/70
> don't use the linkCollection method on the paginator because it's protected before Laravel 8.37.0

- resources/views/livewire/file-list.blade.php
fix overflow clipping for file list dropdown panel
> Fix overflow clipping

- composer.json
- src/LogViewerService.php
- tests/Unit/FilePathsTest.php
> Bug / square bracket fix

- composer.json
- src/Http/Controllers/IsScanRequiredController.php
- src/LogReader.php
- src/MultipleLogReader.php
> fix division by zero when there are empty log files

- config/log-viewer.php
- src/LogViewerServiceProvider.php
Sometimes people want to enable or disable log-viewer with any reason.
So, i have added this option to config with default is active
> add log viewer config activation

- resources/views/index.blade.php
#232 <html> lang tag changed app.locale
> appo locale set-up

- resources/js/stores/files.js
Close mobile sidebar when selected file
> Close mobile sidebar when selected file

- routes/api.php
- src/Http/Controllers/FilesController.php
- src/Http/Controllers/FoldersController.php
- src/Http/Middleware/JsonResourceWithoutWrappingMiddleware.php
- src/LogFile.php
- src/LogIndex.php
- src/Readers/BaseLogReader.php
- tests/Feature/LogFilesControllerTest.php
- tests/Feature/LogFoldersControllerTest.php
> fix JsonResource::withoutWrapping usage spilling outside the package

- src/Logs/LaravelLog.php
Fixes https://github.com/opcodesio/log-viewer/issues/318
> use mb_str_split for multi-byte character support

- src/LogLevels/LaravelLogLevel.php
- src/LogViewerService.php
- src/LogViewerServiceProvider.php
- tests/Feature/Authorization/CanViewLogViewerTest.php
> Security / disable log viewer in production by default

- config/log-viewer.php
- src/Utils/GenerateCacheKey.php
- tests/Unit/GenerateCacheKeyTest.php
> ability to customise the cache key prefix

- src/Http/Controllers/LogsController.php
Fix to correct when a string comes to be paged
> Set type int on paginate

- config/log-viewer.php
- src/LogFile.php
- src/LogViewerService.php
- tests/Feature/LogViewerTest.php
- tests/Unit/FilePathsTest.php
as suggested here - https://github.com/opcodesio/log-viewer/discussions/407
> make it possible to group and rename multiple file includes

- config/log-viewer.php
- resources/js/components/PaginationOptions.vue
- src/Http/Controllers/IndexController.php
- tests/Feature/IndexControllerTest.php
Implements https://github.com/opcodesio/log-viewer/discussions/424
> Ability to configure items per page
